# Generated by Django 2.0.13 on 2019-08-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='user.Story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPageLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30)),
                ('StoryPage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='user.StoryPage')),
            ],
        ),
    ]
